name: Expo React Native CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  expo-ci:
    name: Expo CI
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v5

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Check Expo project
      - name: Run Expo Doctor
        run: npx expo-doctor

      # 5. Export Android project
      - name: Export Expo app
        run: npx expo export --platform android
